/**
 * Make Windows hand magnet links and .torrent files to vi-torrent.
 *
 * There is no popup to build. Browsers generate the "Open vi-torrent?" prompt
 * themselves as soon as the operating system reports a handler for the
 * magnet: scheme - the whole feature is telling Windows that vi-torrent
 * exists, which is what this does.
 *
 * Run explicitly, never on install:
 *
 *   vi-torrent --register
 *   vi-torrent --unregister
 *
 * Silently seizing file associations at install time is the behaviour that
 * makes torrent clients distrusted, and on a published package it is the kind
 * of thing that draws scrutiny. It stays a decision the user makes out loud.
 *
 * Everything is written under HKEY_CURRENT_USER, so this needs no
 * administrator rights and cannot affect other accounts on the machine.
 */
import path from "path";
import { existsSync, writeFileSync, mkdirSync, unlinkSync } from "fs";
import { NO_INSTANCE, resolveStateDir } from "./handoff.js";
import { buildIcon } from "./icon.js";

/** The ProgID our .torrent association points at. */
export const PROGID = "vi-torrent.torrent";

export interface RegistryChange {
  key: string;
  /** The value name, or null for the key's default value. */
  name: string | null;
  data: string;
}

/**
 * Where the `vi-torrent` command actually lives.
 *
 * The registry needs an absolute path: a browser launches handlers without
 * the user's PATH in any dependable state, so `vi-torrent` alone would work
 * from a terminal and fail from Chrome. `where` is asked rather than guessing
 * ~/.bun/bin, which is only right for one installer.
 */
export function resolveExecutable(): string | null {
  const candidates: string[] = [];

  try {
    const result = Bun.spawnSync(["where", "vi-torrent"], { stdout: "pipe", stderr: "pipe" });
    candidates.push(
      ...new TextDecoder().decode(result.stdout)
        .split(/\r?\n/)
        .map(line => line.trim())
        .filter(Boolean),
    );
  } catch {
    // `where` missing is not fatal - the fallback below still applies.
  }

  // Bun's global bin folder, whether or not it is on PATH.
  //
  // `bun install -g` does NOT add this folder to PATH; it prints a warning
  // suggesting you do it yourself, which is easy to miss. The result is a
  // vi-torrent that is genuinely installed but invisible to `where`, and
  // refusing to register at that point would be refusing over a cosmetic
  // problem - the registry stores an absolute path and never consults PATH.
  const home = process.env.USERPROFILE ?? process.env.HOME;
  if (home) candidates.push(path.join(home, ".bun", "bin", "vi-torrent.exe"));

  // A real executable, and one that exists. `where` also lists .bunx and
  // shell shims, which a browser cannot launch directly.
  return candidates.find(c => c.toLowerCase().endsWith(".exe") && existsSync(c))
    ?? candidates.find(existsSync)
    ?? null;
}

/**
 * The registry entries that make up the two associations.
 *
 * Split out from the writing so it can be inspected - and tested - without
 * touching the real registry.
 */
/**
 * The launcher a browser actually runs.
 *
 * `vi-torrent.exe` is a console application, so launching it from a browser
 * makes Windows allocate a console - a window flashes even when all that
 * happens is a link being passed to a session already open. User-reported
 * after the first version shipped.
 *
 * `wscript.exe` is a GUI-subsystem host and allocates no console, so this
 * script is the thing registered. It runs the probe HIDDEN, and only opens a
 * real terminal when there is no window to hand the link to.
 *
 * Written into the state directory rather than the package folder: it embeds
 * an absolute path to the executable, and it must not be lost when the
 * package is upgraded or reinstalled.
 */
export function shimSource(exePath: string): string {
  return [
    "' Opens a magnet link or .torrent in vi-torrent without flashing a console.",
    "' Generated by `vi-torrent --register`. Re-run that after moving or",
    "' reinstalling vi-torrent - the path below is baked in.",
    "Option Explicit",
    "Dim shell, link, exe, code",
    'Set shell = CreateObject("WScript.Shell")',
    "If WScript.Arguments.Count = 0 Then WScript.Quit 2",
    "link = WScript.Arguments(0)",
    `exe = "${exePath}"`,
    "' Hidden: hands the link to a window already open. 10 means none is.",
    `code = shell.Run("""" & exe & """ --handoff """ & link & """", 0, True)`,
    `If code = ${NO_INSTANCE} Then`,
    "  ' Nobody home - open a real terminal, visibly, and let it add the link.",
    "  ' Call, because VBScript rejects parentheses on a Sub whose result is",
    "  ' not assigned - and a compile error here makes wscript raise a MODAL",
    "  ' dialog that waits for someone to click OK.",
    `  Call shell.Run("""" & exe & """ """ & link & """", 1, False)`,
    "End If",
  ].join("\r\n") + "\r\n";
}

/** Where the shim lives. Same state directory the session uses. */
export function shimPath(): string {
  return path.join(resolveStateDir(), "open-link.vbs");
}

/** Where the generated file icon lives. */
export function iconPath(): string {
  return path.join(resolveStateDir(), "vi-torrent.ico");
}

/**
 * Write the icon and return the registry value pointing at it.
 *
 * Without a DefaultIcon, Explorer shows a registered .torrent with whatever
 * generic archive glyph it falls back to - a stock 3D box unrelated to this
 * app, which is what the association looked like when it first shipped.
 *
 * `,0` selects the first icon in the file. It is not optional: without an
 * index Explorer will sometimes resolve the path but not the resource.
 *
 * Returns null if it cannot be written, in which case the DefaultIcon keys
 * are simply skipped - a missing icon is a cosmetic loss, and pointing the
 * registry at a file that is not there is worse than not pointing at all.
 */
function writeIcon(): string | null {
  try {
    const file = iconPath();
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, buildIcon());
    return `${file},0`;
  } catch {
    return null;
  }
}

export function plannedChanges(command: string, icon?: string | null): RegistryChange[] {
  const iconEntries: RegistryChange[] = icon
    ? [
        { key: `HKCU\\Software\\Classes\\${PROGID}\\DefaultIcon`, name: null, data: icon },
        { key: "HKCU\\Software\\Classes\\magnet\\DefaultIcon", name: null, data: icon },
      ]
    : [];
  return [...baseChanges(command), ...iconEntries];
}

function baseChanges(command: string): RegistryChange[] {
  return [
    // The magnet: protocol. "URL Protocol" is the flag that tells Windows
    // this key describes a scheme rather than a file type; without it the
    // handler is ignored and the browser reports no application.
    { key: "HKCU\\Software\\Classes\\magnet", name: null, data: "URL:BitTorrent Magnet Link" },
    { key: "HKCU\\Software\\Classes\\magnet", name: "URL Protocol", data: "" },
    { key: "HKCU\\Software\\Classes\\magnet\\shell\\open\\command", name: null, data: command },

    // .torrent files, through a ProgID rather than hanging the command off
    // the extension directly - the extension is a pointer, and pointing it at
    // our own ProgID is what lets it be handed back cleanly on unregister.
    { key: "HKCU\\Software\\Classes\\.torrent", name: null, data: PROGID },
    { key: `HKCU\\Software\\Classes\\${PROGID}`, name: null, data: "BitTorrent file" },
    { key: `HKCU\\Software\\Classes\\${PROGID}\\shell\\open\\command`, name: null, data: command },
  ];
}

function reg(args: string[]): { ok: boolean; message: string } {
  const result = Bun.spawnSync(["reg", ...args], { stdout: "pipe", stderr: "pipe" });
  const text = new TextDecoder().decode(
    result.exitCode === 0 ? result.stdout : result.stderr,
  ).trim();
  return { ok: result.exitCode === 0, message: text };
}

/** Read a value back, so success is confirmed rather than assumed. */
export function readValue(key: string, name: string | null): string | null {
  const result = Bun.spawnSync(
    ["reg", "query", key, ...(name === null ? ["/ve"] : ["/v", name])],
    { stdout: "pipe", stderr: "pipe" },
  );
  if (result.exitCode !== 0) return null;
  const text = new TextDecoder().decode(result.stdout);
  // Lines look like:  (Default)    REG_SZ    "C:\...\vi-torrent.exe" "%1"
  const match = text.match(/REG_SZ\s+(.*)/);
  return match ? match[1].trimEnd() : "";
}

export interface RegisterResult {
  ok: boolean;
  lines: string[];
}

export function registerHandlers(): RegisterResult {
  const lines: string[] = [];

  if (process.platform !== "win32") {
    return {
      ok: false,
      lines: [
        "--register only works on Windows.",
        "",
        "  On Linux, associations come from a .desktop file rather than the",
        "  registry. See the README for the file to drop in",
        "  ~/.local/share/applications/.",
      ],
    };
  }

  const exePath = resolveExecutable();
  if (!exePath) {
    return {
      ok: false,
      lines: [
        "Could not find the vi-torrent command on PATH.",
        "",
        "  A browser launches handlers without your shell's PATH, so the",
        "  registry needs an absolute path to an installed executable.",
        "",
        "  Install it globally first:",
        "",
        "    bun install -g @vishwanko-9/vi-torrent",
      ],
    };
  }

  // Prefer the windowless shim, but never make registration depend on it:
  // Windows Script Host can be switched off by policy, and a handler pointing
  // at a host that will not run is worse than a console that flashes.
  const { command, windowless, note } = launchCommand(exePath);
  if (note) lines.push(note);

  const icon = writeIcon();

  for (const change of plannedChanges(command, icon)) {
    const args = [
      "add", change.key,
      ...(change.name === null ? ["/ve"] : ["/v", change.name]),
      "/t", "REG_SZ", "/d", change.data, "/f",
    ];
    const written = reg(args);
    if (!written.ok) {
      return {
        ok: false,
        lines: [
          `Failed writing ${change.key}`,
          "",
          "  " + written.message,
        ],
      };
    }
  }

  // Confirm rather than trust. reg.exe reports success on a command string it
  // has re-quoted into something Windows cannot launch, and the failure would
  // then only show up as a browser click doing nothing.
  const commandKey = "HKCU\\Software\\Classes\\magnet\\shell\\open\\command";
  const stored = readValue(commandKey, null);
  if (stored !== command) {
    return {
      ok: false,
      lines: [
        "The handler was written but came back changed, so it may not launch.",
        "",
        `  expected: ${command}`,
        `  stored:   ${stored ?? "(nothing)"}`,
      ],
    };
  }

  lines.push("vi-torrent is now registered with Windows.");
  lines.push("");
  lines.push(`  handler        ${exePath}`);
  lines.push("  magnet: links  click one in a browser");
  lines.push("  .torrent       double-click, or Open from the download bar");
  lines.push(`  window         ${windowless
    ? "none, unless a new one is needed"
    : "a console flashes briefly"}`);
  lines.push(`  icon           ${icon ? iconPath() : "not written - Windows will use its own"}`);
  lines.push("");
  lines.push("  Your browser will ask permission the first time - tick");
  lines.push("  \"Always allow\" and it stops asking.");
  lines.push("");
  lines.push("  Undo any time with:  vi-torrent --unregister");
  return { ok: true, lines };
}

/**
 * What the registry should launch, and whether it avoids a console.
 *
 * Writes the shim as a side effect - there is no point registering a script
 * that is not on disk, and the two must not drift apart.
 */
function launchCommand(exePath: string): {
  command: string;
  windowless: boolean;
  note?: string;
} {
  const direct = `"${exePath}" "%1"`;
  const wscript = path.join(process.env.SystemRoot ?? "C:\\Windows", "System32", "wscript.exe");

  if (!existsSync(wscript)) {
    return {
      command: direct,
      windowless: false,
      note: "Windows Script Host is not present, so links open through\n"
        + "vi-torrent directly and a console window flashes briefly.\n",
    };
  }

  try {
    const shim = shimPath();
    mkdirSync(path.dirname(shim), { recursive: true });
    writeFileSync(shim, shimSource(exePath), "utf8");
    return { command: `"${wscript}" "${shim}" "%1"`, windowless: true };
  } catch {
    return {
      command: direct,
      windowless: false,
      note: "Could not write the launcher script, so links open through\n"
        + "vi-torrent directly and a console window flashes briefly.\n",
    };
  }
}

export function unregisterHandlers(): RegisterResult {
  if (process.platform !== "win32") {
    return { ok: false, lines: ["--unregister only works on Windows."] };
  }

  // Only the keys we created. The .torrent extension key is deliberately NOT
  // deleted - another client may have owned it before us, and removing it
  // would take their association down with ours.
  const owned = [
    "HKCU\\Software\\Classes\\magnet",
    `HKCU\\Software\\Classes\\${PROGID}`,
  ];
  for (const key of owned) reg(["delete", key, "/f"]);

  // The generated launcher goes too - nothing points at it any more, and
  // leaving a script behind that silently launches an application is exactly
  // what an uninstall is supposed to clear away.
  for (const generated of [shimPath(), iconPath()]) {
    try {
      unlinkSync(generated);
    } catch {
      // Never written, or already gone.
    }
  }

  const lines = ["vi-torrent is no longer registered."];
  if (readValue("HKCU\\Software\\Classes\\.torrent", null) === PROGID) {
    lines.push("");
    lines.push("  .torrent still points at vi-torrent but the handler is gone,");
    lines.push("  so Windows will ask you to choose an application. Pick one");
    lines.push("  with \"Always use this app\" to settle it.");
  }
  return { ok: true, lines };
}

/** The Linux equivalent, printed rather than written - see README. */
export function desktopEntry(exePath: string): string {
  return [
    "[Desktop Entry]",
    "Type=Application",
    "Name=vi-torrent",
    "Comment=BitTorrent client in the terminal",
    `Exec=${exePath} %u`,
    "Terminal=true",
    "MimeType=x-scheme-handler/magnet;application/x-bittorrent;",
    "Categories=Network;FileTransfer;",
  ].join("\n") + "\n";
}
